# yaml-language-server: $schema=../src/assets/openmct-configuration-schema.json
openmct:
  version: '4.1.0'
  plugins:
  - openmct.plugins.Snow # Theme: 'Snow', 'Espresso' or 'Maelstrom'
  - openmct.plugins.ObjectMigration
  - openmct.plugins.ClearData:
      options:
        - ['table', 'telemetry.plot.overlay', 'telemetry.plot.stacked', 'vista.packetSummaryEvents', 'vista.dataProducts', 'vista.packets', 'vista.frameSummary', 'vista.frameWatch', 'vista.chanTableGroup']
        - indicator: false
  - openmct.plugins.DisplayLayout:
      options:
        showAsView:
          - summary-widget
          - vista.packetSummaryEvents
          - vista.dataProducts
          - vista.packets
          - vista.frameSummary
          - vista.frameWatch
  - openmct.plugins.Filters:
      options:
        - - vista.alarmsView
          - telemetry.plot.overlay
          - table
          - vista.chanTableGroup
          - vista.commandEventsView
          - vista.messagesView
          - vista.evrView
  - openmct.plugins.UTCTimeSystem
  - openmct.plugins.Notebook
  - openmct.plugins.Clock:
      options:
        useClockIndicator: false
  - openmct.plugins.DefaultRootName:
      options: ['VISTA']
  # Open MCT for MCWS Plugin
  - openmct-mcws-plugin:
      options:
        camUrl: ''
        mcwsUrl: ''
        namespaces:
          - key: 'r50-dev'
            name: 'R5.0 Shared'
            url: ''
          - userNamespace: true
            key: 'r50-dev'
            name: 'R5.0 Users'
            url: ''
  # Optional Dev Plugins
  # - openmct.plugins.LocalStorage
  # - openmct.plugins.MyItems
  # Open MCT for MCWS Plugin Options